# Generated by Django 3.0.3 on 2021-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210715_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Restaurację', 'verbose_name_plural': 'Restauracje'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='describtion',
            field=models.TextField(verbose_name='Opis restauracji'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Opublikowana'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa restauracji'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany'),
        ),
    ]
